name: driver_app
description: "Çekici Driver Application"
publish_to: 'none'

version: 1.0.0+6

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.0
  flutter_riverpod: ^2.5.1
  google_maps_flutter: ^2.9.0
  go_router: ^14.2.7
  url_launcher: ^6.3.0
  flutter_dotenv: ^5.1.0
  agora_rtc_engine: ^6.3.0
  permission_handler: ^11.3.1
  cached_network_image: ^3.3.1
  lottie: ^3.1.0
  connectivity_plus: ^6.0.3
  geolocator: ^13.0.1
  image_picker: ^1.1.2
  map_launcher: ^3.4.0
  flutter_svg: ^2.0.10
  flutter_local_notifications: ^17.2.2

  # Monorepo packages:
  shared_models:
    path: ../../packages/shared_models
  shared_services:
    path: ../../packages/shared_services
  shared_ui:
    path: ../../packages/shared_ui_light
  firebase_core: ^3.11.0
  firebase_messaging: ^15.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/bg_alarm2.mp3
